/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js normally; it is checked in so the scaffold
// type-checks before the first local dev run.
